autotimer: Create tuple as argument
File "/usr/lib/enigma2/python/Plugins/Extensions/AutoTimer/AutoTimerEditor.py", line 188, in __init__
    self.createSetup(timer)
  File "/usr/lib/enigma2/python/Plugins/Extensions/AutoTimer/AutoTimerEditor.py", line 232, in createSetup
    begin = mktime(now)
TypeError: Tuple or struct_time argument required