NetworkBrowser.py: Use sorted() instead of sort()
File "/usr/lib/enigma2/python/Plugins/SystemPlugins/NetworkBrowser/NetworkBrowser.py", line 412, in passwordQuestion
    self.updateNetworkList()
  File "/usr/lib/enigma2/python/Plugins/SystemPlugins/NetworkBrowser/NetworkBrowser.py", line 288, in updateNetworkList
    self.network.keys().sort()
AttributeError: 'dict_keys' object has no attribute 'sort'