shoutcast: Fix crash when recording stream
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/SHOUTcast/plugin.py", line 405, in streamripperDataAvail
TypeError: a bytes-like object is required, not 'str'