bitrate needs to be an integer.
Fixes:
File "/usr/lib/enigma2/python/Plugins/SystemPlugins/TranscodingSetup/plugin.py", line 98, in __init__
    ValueError: invalid literal for int() with base 10: '4000.0'